spring:
  profiles:
    active: dev
  application:
    name: user-service

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/users-qua-8888;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username: sa
    password: password

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.springframework: INFO
    ma.gov.pfe: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
